### 查询课程信息
POST {{content_host}}/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

<> 2023-03-21T094008.200.json
<> 2023-03-21T091457.200.json
<> 2023-03-21T091450.200.json
<> 2023-03-21T091430.404.html
<> 2023-03-21T091340.404.html

### 查询课程分类
GET {{content_host}}/content/course-category/tree-nodes

<> 2023-03-24T084548.200.json
<> 2023-03-24T084031.404.json
<> 2023-03-24T083811.404.json
<> 2023-03-24T083736.404.html
<> 2023-03-24T083639.404.html

### 添加课程基本信息
POST {{content_host}}/content/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T150732.200.json
<> 2023-03-24T150500.200.json
<> 2023-03-24T145605.404.html
<> 2023-03-24T145446.404.html

### 根据id查询课程基本信息
GET {{content_host}}/content/course/125

<> 2023-03-27T093753.200.json
<> 2023-03-27T093724.200.json
<> 2023-03-27T093707.404.html

### 修改课程基本信息
PUT {{content_host}}/content/course
Content-Type: application/json

{
  "id": 121,
  "name": "111name",
  "tags": "111tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "111description",
  "users": "111users11111111",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "111qq",
  "wechat": "111wechat",
  "phone": "111phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-27T205859.200.json
<> 2023-03-27T205845.500.json

###
GET {{content_host}}/content/teachplan/25/tree-nodes

<> 2023-03-30T085502.200.json
