GET http://localhost:63040/content/teachplan/25/tree-nodes

<> 2023-03-30T085502.200.json

###

PUT http://localhost:63040/content/course
Content-Type: application/json

{
  "id": 121,
  "name": "111name",
  "tags": "111tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "111description",
  "users": "111users11111111",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "111qq",
  "wechat": "111wechat",
  "phone": "111phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-27T205859.200.json

###

PUT http://localhost:63040/content/course
Content-Type: application/json

{
  "id": 121,
  "name": "111name",
  "tags": "111tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "111description",
  "users": "111users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "111qq",
  "wechat": "111wechat",
  "phone": "111phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-27T205845.500.json

###

GET http://localhost:63040/content/course/125

<> 2023-03-27T093753.200.json

###

GET http://localhost:63040/content/course/1

<> 2023-03-27T093724.200.json

###

GET http://localhost:63040/course/1

<> 2023-03-27T093707.404.html

###

POST http://localhost:63040/content/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T150732.200.json

###

POST http://localhost:63040/content/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T150500.200.json

###

POST http://localhost:63040/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T145605.404.html

###

POST http://localhost:63040/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002",
}

<> 2023-03-24T145446.404.html

###

GET http://localhost:63040/content/course-category/tree-nodes

<> 2023-03-24T084548.200.json

###

GET http://localhost:63040/content/course-category/tree-nodes

<> 2023-03-24T084031.404.json

###

GET http://localhost:63040/content/course-category/tree-nodes

<> 2023-03-24T083811.404.json

###

GET http://localhost:63040/course-category/tree-nodes

<> 2023-03-24T083736.404.html

###

GET http://localhost:63040/course-category/tree-nodes

<> 2023-03-24T083639.404.html

###

