POST http://localhost:63010/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

<> 2023-04-08T125117.200.json

###

POST http://localhost:63010/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

<> 2023-04-08T124644.500.json

###

POST http://localhost:63010/content/course/list?pageNo=1&pageSize=10
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": "203001"
}

<> 2023-04-08T095056.404.json

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 117,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "1",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 0,
  "pname" : "修改111名",
  "startTime" : null,
  "status" : null,
  "id" : 297
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 117,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "1",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 0,
  "pname" : "修改名111",
  "startTime" : null,
  "status" : null,
  "id" : 297
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 117,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "1",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 0,
  "pname" : "修改名111",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 117,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "1",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 0,
  "pname" : "修改名",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 297
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 117,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "1",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 0,
  "pname" : "修改名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 117,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "1",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 0,
  "pname" : "修改章节名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 291
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 22,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "2",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 237,
  "pname" : "第1节修改名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}

###

POST http://localhost:63040/content/teachplan
Content-Type: application/json

{
  "changeDate" : null,
  "courseId" : 22,
  "cousePubId" : null,
  "createDate" : null,
  "ctlBarShow" : false,
  "ctlEditTitle" : true,
  "endTime" : null,
  "grade" : "2",
  "isPreview" : "1",
  "mediaType" : "",
  "orderby" : 1,
  "parentid" : 237,
  "pname" : "第1节修改名称",
  "startTime" : null,
  "status" : null,
  "teachPlanId" : 240
}

<> 2023-04-01T163204.500.json

###

GET http://localhost:63040/content/teachplan/25/tree-nodes

<> 2023-03-30T085502.200.json

###

PUT http://localhost:63040/content/course
Content-Type: application/json

{
  "id": 121,
  "name": "111name",
  "tags": "111tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "111description",
  "users": "111users11111111",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "111qq",
  "wechat": "111wechat",
  "phone": "111phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-27T205859.200.json

###

PUT http://localhost:63040/content/course
Content-Type: application/json

{
  "id": 121,
  "name": "111name",
  "tags": "111tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "111description",
  "users": "111users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "111qq",
  "wechat": "111wechat",
  "phone": "111phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-27T205845.500.json

###

GET http://localhost:63040/content/course/125

<> 2023-03-27T093753.200.json

###

GET http://localhost:63040/content/course/1

<> 2023-03-27T093724.200.json

###

GET http://localhost:63040/course/1

<> 2023-03-27T093707.404.html

###

POST http://localhost:63040/content/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T150732.200.json

###

POST http://localhost:63040/content/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T150500.200.json

###

POST http://localhost:63040/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002"
}

<> 2023-03-24T145605.404.html

###

POST http://localhost:63040/course
Content-Type: application/json

{
  "name": "name",
  "tags": "tag",
  "mt": "1-1",
  "st": "1-1-1",
  "grade": "204001",
  "description": "description",
  "users": "users",
  "pic": "",
  "charge": "201000",
  "originalPrice": 0,
  "price": 0,
  "qq": "qq",
  "wechat": "wechat",
  "phone": "phone",
  "validDays": 365,
  "teachmode": "200002",
}

<> 2023-03-24T145446.404.html

###

GET http://localhost:63040/content/course-category/tree-nodes

<> 2023-03-24T084548.200.json

###

GET http://localhost:63040/content/course-category/tree-nodes

<> 2023-03-24T084031.404.json

###

GET http://localhost:63040/content/course-category/tree-nodes

<> 2023-03-24T083811.404.json

###

GET http://localhost:63040/course-category/tree-nodes

<> 2023-03-24T083736.404.html

###

GET http://localhost:63040/course-category/tree-nodes

<> 2023-03-24T083639.404.html

###

